global using Company.Data.Interfaces;
global using Company.Data.Entities;
global using Company.Data.Contexts;
global using Company.Data.Services;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using System.Linq.Expressions;
global using AutoMapper;
